language: ruby
script: "bundle install --gemfile .gemfile && BUNDLE_GEMFILE=.gemfile bundle exec rake test SPEC_OPTS='--format documentation --color --backtrace'"
rvm:
 - 1.9.3
 - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
notifications:
  email: false
